### ISSUE TITLE
[REQUEST] Prebuild binaries

### ISSUE THREAD

**Issue by HemanthJabalpuri** [LonelyFool/lpunpack_and_lpmake#3]
@LonelyFool
Thanks for the build script.

Along with it, please share prebuilt binaries as releases for both Linux and Windows too.

Thanks

**Comment by LonelyFool** [comment]
Linux: https://github.com/Exynos-nigg/lpunpack-lpmake-mirror

**Comment by yossi66a** [comment]
Hi can i install this on windows?

**Comment by peterbetos** [comment]
Any Android 11 version of the lpmake? Android 10 version of the lpmake causes kinstalldeviceopenerror on Android 12 super images
