### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by alex161rus** [LonelyFool/lpunpack_and_lpmake#6]
Hi. is it possible to compile the code for windows? it would be very convenient. I don’t know how. I ask for your help.

**Comment by yossi66a** [comment]
im struggling to install it on windows thru linux shell please help, thanks

**Comment by alex161rus** [comment]
> Я изо всех сил пытаюсь установить его на Windows через оболочку Linux, пожалуйста, помогите, спасибо

Установи wsl, запусти его. Первичная настройка linux, логин и пароль установи.

Можешь воспользоваться моим скриптом для автоматической сборки.
https://4pda.to/forum/index.php?showtopic=636743&view=findpost&p=109641315

**Comment by yossi66a** [comment]
Hi thanks so much for your help,
i have already the linux shell on my pc and still not going
Thanks very much

**Comment by peterbetos** [comment]
Is the make script even able to see the subfolder directories? I see a lot of errors that is caused by the script not seeing the subfolder structure even though it's there.

![Screenshot (19)](https://user-images.githubusercontent.com/3241327/140619898-dd10ab40-b837-40bd-8cd7-64ed05232c1a.jpg)

**Comment by affggh** [comment]
Hi there, I've compiled it successfully on cygwin64,and test it worked well.

**Comment by affggh** [comment]
Hi there, I've compiled it successfully on cygwin64,and test it worked well.

**Comment by alex161rus** [comment]
> Привет, я успешно скомпилировал его на cygwin64 и протестировал его.

Можешь поделиться? Спасибо

**Comment by peterbetos** [comment]
> Hi there, I've compiled it successfully on cygwin64,and test it worked well.

What dependencies have you installed aside from clang?

**Comment by LonelyFool** [comment]
> > Привет, я успешно скомпилировал его на cygwin64 и протестировал его。
> 
> Можешь поделиться？Спасибо

https://github.com/affggh/lpmake_and_lpunpack_cygwin

**Comment by peterbetos** [comment]
> > > Привет, я успешно скомпилировал его на cygwin64 и протестировал его。
> > 
> > 
> > Можешь поделиться？Спасибо
> 
> https://github.com/affggh/lpmake_and_lpunpack_cygwin

Thanks, hopefully this is the Android 11 one

**Comment by alex161rus** [comment]
> > > Привет, я успешно скомпилировал его на cygwin64 и протестировал его。
> > 
> > 
> > Можешь поделиться？ Спасибо
> 
> https://github.com/affggh/lpmake_and_lpunpack_cygwin

СПАСИБО друг. Вот мой скрип для linux или windows wsl. 
Он сам определяет исходный размер super, и собирает всё из списка. Может пригодится 
https://drive.google.com/file/d/1Hk7I-MT6GtS22C5ONrM_kOUFFPCqb7n4/view?usp=drivesdk

**Comment by affggh** [comment]
> > Hi there, I've compiled it successfully on cygwin64,and test it worked well.
> 
> What dependencies have you installed aside from clang?

I changed lot of library,first time it even not work so I fetch sparse and partitiontools libary from aosp

**Comment by affggh** [comment]
> > > > Привет, я успешно скомпилировал его на cygwin64 и протестировал его。
> > > 
> > > 
> > > Можешь поделиться？Спасибо
> > 
> > 
> > https://github.com/affggh/lpmake_and_lpunpack_cygwin
> 
> Thanks, hopefully this is the Android 11 one

this source fetch from this repository,master branch

**Comment by affggh** [comment]
> > > Привет, я успешно скомпилировал его на cygwin64 и протестировал его。
> > 
> > 
> > Можешь поделиться？Спасибо
> 
> https://github.com/affggh/lpmake_and_lpunpack_cygwin

感谢大佬，大佬牛逼

**Comment by alex161rus** [comment]
Версия для win64 работает прекрасно. Спасибо https://github.com/affggh
